### PR TITLE
Add headersynthwave aa1 to master

### LINKED ISSUE #20: There should be a header Synthwave
**Is your feature request related to a problem? Please describe.**
It would be nice, if the old erebos header could be reworked in to a new design, which would fit our standards and style.

**Describe the solution you'd like**
Update the look of the Header into direction of Synthwave, so that it gives the Erebos website a new kind of touch.

**Additional context**
Header

### PR DESCRIPTION
**Pull request by petschna**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently the HeaderSynthwave does not fit in the current style of the website. #20

**What is the new behavior (if this is a feature change)?**
- Now there is a HeaderSynthwave which has been updated to fit the style requirements. Closes #20

### CODE REVIEW

**Review by petschna — COMMENTED** [review]
Should be ok to merge.

**Review by petute — APPROVED** [review]
Should be ok to merge.

**Review by petschna — COMMENTED** [review]
Should be ok to merge.

**Review by petute — APPROVED** [review]
Should be ok to merge.

**Review by petschna — COMMENTED** [review]
Should be ok to merge.

**Review by petute — APPROVED** [review]
Should be ok to merge.

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Pull request merged**
