### PR TITLE
Add asset to motd to master

### LINKED ISSUE #22: There should be more content in SectionMotd
**Is your feature request related to a problem? Please describe.**
It would be nice to fusion the style Synthwave and Vaporwave in SectionMotd, which is between the HeaderSynthwave section and the Vaporwave SectionSharingan.

**Describe the solution you'd like**
Update the look of the SectionMotd so that it contains Synthwave and Vaporwave.

### PR DESCRIPTION
**Pull request by petschna**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently the SectionMotd does not combine the aspects of the Vaporwave and Synthwave style. #22 

**What is the new behavior (if this is a feature change)?**
- Now there is a SectionMotd which has been updated to fit the style requirements. Closes #22

### CODE REVIEW

**Review by petschna — COMMENTED** [review]
Should be ok to merge.

**Review by petute — APPROVED** [review]
Should be ok to merge.

**Review by petschna — COMMENTED** [review]
Should be ok to merge.

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Review by petute — APPROVED** [review]
Should be ok to merge.

**Pull request merged**
